### ISSUE TITLE
No indication of registration of a worker on Waterfox 56.2.0 or Firefox 60.0.1

### ISSUE THREAD

**Issue by grahamperrin** [google/service-worker-detector#9] opened 2018-05-20 17:30 UTC
[No Indicator on Firefox · Issue #8 · google/service-worker-detector](https://github.com/google/service-worker-detector/issues/8) was closed as not reproducible. 

I do not get a construction worker icon to appear, when expected, in the <strike>address field </strike>address bar in either of the following on FreeBSD-CURRENT: 

- Waterfox 56.2.0.7 (56.2.0 build 20180515213058)
- Firefox  60.0.1,1 (60.0.1). 

With Twitter as an example: 

1. launch the browser
2. refrain from opening any tab to Twitter
3. about:serviceworkers
4. find and un-register the worker for `https://twitter.com/`
5. in a separate tab, visit https://twitter.com/ – load the page completely at least once, maybe reload
7. bring about:serviceworkers to front, reload the page, find the newly registered worker for Twitter
8. bring the Twitter tab to front, reload

## In Waterfox

No icon in the address bar. At first I suspected an extension conflict, but then I found … 

## In Firefox

![2018-05-20 18 18 39](https://user-images.githubusercontent.com/192271/40281482-673b92a2-5c5a-11e8-843c-c89d3fed2c91.png)

> 🛏 ❌ 👷  No active Service Worker found.

Soft reloads do not cause an icon to appear in the bar. 

Should a notification of some sort – at least, appearance of the page action icon in the address bar – occur when registration/installation is detected on Firefox? From the description, I assume so: 

> … detects if a website registers a Service Worker …

– and both screenshots ([of Chrome, at addons.mozilla.org](https://github.com/google/service-worker-detector/issues/10)) include the construction worker icon, with the first shot showing: 

> **Events**
> 
> ☐ activate
> ☐ fetch
> ☑ install

**Comment by grahamperrin** [comment] 2018-05-20 20:08
Interestingly, in Waterfox I got this for a domain where pages do not load when expected: 

![2018-05-20 19 53 35](https://user-images.githubusercontent.com/192271/40283072-ae20aeee-5c70-11e8-9dd2-fc3f92c52cbe.png)

(The non-appearance of page content is neither an issue with this extension nor, AFAICT, an issue with Waterfox.) 

Two frames from a subsequent screen recording: 

![2018-05-20 19 55 17 frame a](https://user-images.githubusercontent.com/192271/40283140-7e291b62-5c71-11e8-807d-58a01fb4b0ae.png)

![2018-05-20 19 55 17 frame b](https://user-images.githubusercontent.com/192271/40283143-85ae3f3e-5c71-11e8-852a-51b51cbd7160.png)

<strike>… so _maybe_ the issue, at least for Waterfox, is that an expected preference is both: 

1. not enabled by default; **and**
2. not easily accessible (no GUI) until after a different preference causes appearance of the page icon button. 

(Does that make sense?)</strike>

## Postscript

I imagined, wrongly, that the checkboxes would (a) be persistent; and (b) determine when the construction worker icon should surface. 

Eventually I realised that the checkboxes are non-persistent, to temporarily highlight relevant strings in the pop-up. 

OT from Service Worker Detector, `https://github.com/MrAlex94/Waterfox/issues/581` is _'Corrupted Content Error' or 'Cannot load app' …_

**Comment by tomayac** [comment] 2018-05-23 13:46
Twitter currently might just register a service worker for its [mobile site](https://mobile.twitter.com/home), not the desktop site, which probably is the reason why you're not seeing the icon pop up. 

If you try with a simple PWA like @paulkinlan's [Airhorner](https://airhorner.com/), you can see it works fine on Firefox as well as Waterfox:

![screen shot 2018-05-23 at 15 36 59](https://user-images.githubusercontent.com/145676/40428186-05edb636-5ea0-11e8-97e3-0f08432e5c8b.png)
![screen shot 2018-05-23 at 15 40 54](https://user-images.githubusercontent.com/145676/40428188-06706536-5ea0-11e8-91ca-f8e07a9e5313.png)

This is working as intended, closing the issue.

**Closed as completed by tomayac** 2018-05-23 13:46 UTC

**Comment by grahamperrin** [comment] 2018-05-24 04:21
@tomayac thanks for the speedy feedback, and example 👍 

Here, Service Worker Detector 2.3.14 added to a clean profile with Firefox 60.0.1 (64-bit) on FreeBSD-CURRENT: 

![2018-05-24 05 16 08 the air horner - mozilla firefox](https://user-images.githubusercontent.com/192271/40464261-1dbf5e0a-5f12-11e8-81ef-dea0b3ab40dc.png)

Please, am I missing something? 

~~I'll test on a Mac …~~

## Postscript

After a while, but (unless I'm losing my mind) **not** after a reload of the page, the construction worker did appear. 

I'll aim to make the issue, the non-appearance, more reproducible.

**Comment by grahamperrin** [comment] 2018-05-24 05:04
## Twitter

> Twitter currently might just register a service worker for its mobile site, not the desktop site, which probably is the reason why you're not seeing the icon pop up.

Here, with the same _fairly_ clean profile (visibly dirtied only by the astonishing fragility of favicons) there is registration for Twitter: 

![2018-05-24 05 47 56 waterfox](https://user-images.githubusercontent.com/192271/40465009-6a74099a-5f16-11e8-8779-b623d35ed18a.png)

– and the construction worker icon does not surface, from the menu, to the address bar. I'm reasonably certain of the non-surface because I can: 

1. un-register the service worker
2. bring the https://twitter.com/ tab to the front
3. click the **Page actions** menu icon
4. observe the 'No active Service Worker found.' state
5. continue observing that state whilst repeatedly using <kbd>Control</kbd>-<kbd>R</kbd> to reload the page.

Please: is the extension designed to surface the icon only whilst a _registered_ Service Worker is **also** _active_?

**Comment by tomayac** [comment] 2018-05-24 10:56
> is the extension designed to surface the icon only whilst a registered Service Worker is also active?

@grahamperrin Correct, the extension only triggers when `navigator.serviceWorker.controller` is no longer `null`, *i.e.*, as soon as the service worker becomes active ([documentation](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/controller)).

**Comment by grahamperrin** [comment] 2018-05-24 19:55
OK, thanks! 

Sorry for the over-focus on the Service Worker with scope `https://twitter.com/`. I can't guess when it will be activated …

… the Service Worker with scope `https://mobile.twitter.com/` **does** activate, here, with a simple logged in visit to https://mobile.twitter.com/home – I have the construction worker icon in the address bar of Waterfox. 

----

I'll ignore the non- (or delayed) activation of the worker at https://airhorner.com/ – couldn't make the oddity reproducible, in Firefox. It works in Waterfox. 

----

I sped through all thirty-something Service Worker registrations in my main Waterfox profile. 

The majority do lead to visibility of a construction worker icon. For the handful that do not, I might raise a separate issue (enhancement request), nothing too complicated …
